#!/bin/bash
# setup.sh - macOS configuration wizard for Scribe PDF to Logseq

# Get the parent folder (project root)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PARENT_FOLDER="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PARENT_FOLDER/settings/config.sh"

# Function to prompt for user input with a default value
prompt_input() {
    local message="$1"
    local default="$2"
    local input
    read -rp "$message [$default]: " input
    if [ -z "$input" ]; then
        echo "$default"
    else
        echo "$input"
    fi
}

echo ""
echo "=== Scribe PDF to Logseq - macOS Configuration ==="
echo "Press enter to accept default values."
echo ""

# Collect user inputs
deviceNamePattern=$(prompt_input "Enter Device Name Pattern" "Kindle")
updateLogSeq=$(prompt_input "Add Notebooks to LogSeq (Yes/No)" "Yes")

if [ "$updateLogSeq" = "Yes" ]; then
    logSeqFolder=$(prompt_input "Enter LogSeq Graph Folder" "$HOME/LogSeq")
    gitLogSeq=$(prompt_input "Push logseq changes to git (Yes/No)" "Yes")
    gitBranch=$(prompt_input "Git branch name" "main")
fi

echo ""
echo "!!! WARNING !!!"
echo "!!! These are advanced parameters, unless you know what you're doing, accept the defaults by pressing enter !!!"
echo "!!! WARNING !!!"
echo ""

notebooksFolderName=$(prompt_input "Enter Notebooks Folder Name" ".notebooks")
internalStorageFolderName=$(prompt_input "Enter Internal Storage Folder Name" "Internal Storage")
destinationPath=$(prompt_input "Enter Destination Path" "$PARENT_FOLDER/exported_notebooks")
sourcePdfFolder=$(prompt_input "Enter PDF storage Folder" "$PARENT_FOLDER/pdf")
outputEpubDirectory=$(prompt_input "Enter EPUB storage Folder" "$PARENT_FOLDER/epub")
guidPattern=$(prompt_input "Enter GUID Pattern" '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')
nbkFileName=$(prompt_input "Enter NBK File Name" "nbk")

# macOS Calibre paths
calibrePath=$(prompt_input "Enter Path to Calibre Debug" "/Applications/calibre.app/Contents/MacOS/calibre-debug")
ebookConvertPath=$(prompt_input "Path to the ebook-convert executable" "/Applications/calibre.app/Contents/MacOS/ebook-convert")
pluginName=$(prompt_input "Name of the Calibre plugin to use" "KFX Input")

if [ "$updateLogSeq" = "Yes" ]; then
    destinationFolder=$(prompt_input "Enter LogSeq assets PDF Folder" "$logSeqFolder/assets/pdf")
    logSeqPage=$(prompt_input "Enter Logseq Page Name for Scribe Notebooks" "Scribe Notebooks")
    markdownFile=$(prompt_input "Enter Logseq Markdown File Path" "$logSeqFolder/pages/$logSeqPage.md")
    repoPath=$(prompt_input "Enter LogSeq Git Repository Path" "$logSeqFolder")
fi

echo ""
echo "=== Google Calendar Sync ==="
syncCalendar=$(prompt_input "Sync Google Calendar to Scribe PDF (Yes/No)" "Yes")

if [ "$syncCalendar" = "Yes" ]; then
    calendarPdfName=$(prompt_input "Calendar PDF base name" "Calendar")
    calendarMonths=$(prompt_input "Number of months to generate (1-3)" "1")
    echo ""
    echo "To use Google Calendar, you need a credentials.json file from Google Cloud Console."
    echo "Place it at: $PARENT_FOLDER/settings/credentials.json"
    echo "(You can also use a local events.json file instead — see README)"
fi

# Ensure the settings directory exists
SETTINGS_DIR="$(dirname "$CONFIG_FILE")"
mkdir -p "$SETTINGS_DIR"

# Write the config file
cat > "$CONFIG_FILE" << CONFIGEOF
# Config file generated by setup.sh
DEVICE_NAME_PATTERN="$deviceNamePattern"
UPDATE_LOGSEQ="$updateLogSeq"
GIT_LOGSEQ="$gitLogSeq"
GIT_BRANCH="$gitBranch"
LOGSEQ_FOLDER="$logSeqFolder"
NOTEBOOKS_FOLDER_NAME="$notebooksFolderName"
INTERNAL_STORAGE_FOLDER_NAME="$internalStorageFolderName"
DESTINATION_PATH="$destinationPath"
SOURCE_PDF_FOLDER="$sourcePdfFolder"
OUTPUT_EPUB_DIRECTORY="$outputEpubDirectory"
GUID_PATTERN='$guidPattern'
NBK_FILE_NAME="$nbkFileName"
CALIBRE_PATH="$calibrePath"
EBOOK_CONVERT_PATH="$ebookConvertPath"
PLUGIN_NAME="$pluginName"
DESTINATION_FOLDER="$destinationFolder"
LOGSEQ_PAGE="$logSeqPage"
MARKDOWN_FILE="$markdownFile"
REPO_PATH="$repoPath"
SETTINGS_DIRECTORY="$SETTINGS_DIR"
SCRIPT_PATH="$SCRIPT_DIR"
SYNC_CALENDAR="$syncCalendar"
CALENDAR_PDF_NAME="$calendarPdfName"
CALENDAR_MONTHS="$calendarMonths"
CONFIGEOF

echo ""
echo "Configuration file has been created at $CONFIG_FILE"
echo "You can now run: bash script/scribe_watcher.sh"
